#!/bin/bash
# run-comfyui.sh
# Generated by GitHub Copilot

# Activate venv
source .venv/bin/activate

# Ensure Sox is in PATH (should be if installed via apt)
export PATH=$PATH:/usr/bin

# Set optimized settings for Flash Attention 2
export FLASH_ATTENTION_FORCE_UNROLL=1 # Optional performance tweak

# Run ComfyUI
echo "Starting ComfyUI on http://127.0.0.1:8188 ..."
python ComfyUI/main.py --port 8188 --listen 127.0.0.1
